### ISSUE TITLE
What boards are compatible?

### ISSUE THREAD

**Issue by SamGurdus1** [kinnounko/esp8266-captive-attack#1]
What board did you use when making this? Could you provide a link to where to purchase one?

**Comment by gboy18** [comment]
I'm going to try this on my Raspberry Pi right now.

**Comment by kinnounko** [comment]
Sorry for the very late reply. I used the NodeMCU ESP8266. I bought it from Amazon, here's a link; https://www.amazon.com/s?k=nodemcu+esp8266&ref=nb_sb_noss
